#!/bin/sh

CURDIR=`dirname $0`
cd $CURDIR/..

echo `pwd`

exec java $JAVA_OPTS -Ddw.http.port=$PORT \
    -Ddw.http.adminPort=$PORT \
    -Ddw.http.adminUsername=$ADMIN_USERNAME \
    -Ddw.http.adminPassword=$ADMIN_PASSWORD \
    -jar target/showmyrequest-1.0.jar server \
    app/config.yml
